// Demo data for FumiPro NC – used when Sanity is not configured
// Replace with real Sanity data by setting SANITY_PROJECT_ID in .env

export const business = {
  name: "FumiPro NC",
  area: "Charlotte, NC",
  address: "4521 Sharon Rd, Charlotte, NC 28211",
  phone: "(704) 555-0192",
  mapsUrl: "https://maps.google.com/?q=Charlotte,NC+28211",
  hoursText: "Lun–Vie 8:00 a 17:00 · Sáb 8:00 a 12:00 · Dom cerrado",
  whatsappCitasNumber: "17045550192",
  whatsappFallbackNumber: "17045550192",
  whatsappGeneralMessage: "Hola, quiero solicitar un servicio de fumigación en {negocio}. ¿Tienen disponibilidad?",
  homeHeroEyebrow: "Control de plagas profesional",
  homeHeroTitle: "Protección total contra plagas en tu hogar y negocio",
  homeHeroSubtitle: "Más de 10 años eliminando plagas en Charlotte, NC. Roedores, cucarachas, termitas, chinches y más — garantía de resultados.",
  homeHeroImageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1800&q=80",
  homePrimaryCtaText: "Solicitar inspección",
  homePrimaryCtaUrl: "/agendar",
  homeSecondaryCtaText: "Nuestros servicios",
  homeSecondaryCtaUrl: "/servicios",
  homePromotionsTitle: "Ofertas especiales",
  homePromotionsSubtitle: "Aprovecha nuestros paquetes de fumigación con garantía de resultados.",
  homeGoogleReviewsTitle: "Reseñas de nuestros clientes",
  homeGoogleReviewsSubtitle: "Opiniones de clientes reales en Charlotte, NC publicadas en Google Maps.",
  homeGoogleReviewsCtaText: "Ver reseñas en Google",
  footerTagline: "Control de plagas profesional en Charlotte, NC",
  facebookUrl: "https://facebook.com",
  instagramUrl: "https://instagram.com",
};

export const about = {
  title: "Sobre FumiPro NC",
  intro: "Somos una empresa de control de plagas en Charlotte, NC con técnicos certificados, atención rápida y garantía de resultados en cada tratamiento.",
  secondary: "Eliminamos roedores, cucarachas, termitas, chinches, hormigas y avispas con métodos seguros, probados y certificados para proteger a tu familia y mascotas.",
  mainImageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=80",
  keyPoints: [
    "Técnicos certificados y con experiencia",
    "Productos seguros para familia y mascotas",
    "Garantía de resultados incluida",
    "Atención el mismo día o siguiente",
    "Servicio residencial y comercial",
    "Inspección gratuita en tu primera visita",
  ],
  titleEn: "About FumiPro NC",
  introEn: "We are a pest control company in Charlotte, NC with certified technicians, fast response and guaranteed results on every treatment.",
  secondaryEn: "We eliminate rodents, cockroaches, termites, bed bugs, ants and wasps using safe, proven and certified methods to protect your family and pets.",
  keyPointsEn: [
    "Certified and experienced technicians",
    "Safe products for family and pets",
    "Guaranteed results included",
    "Same-day or next-day service",
    "Residential and commercial service",
    "Free inspection on your first visit",
  ],
  specialistsTitle: "Nuestros técnicos",
  specialistsSubtitle: "Conoce a los técnicos certificados que protegen tu hogar o negocio en Charlotte, NC.",
  servicesTitle: "Servicios de fumigación",
  servicesSubtitle: "Tratamientos profesionales para todo tipo de plaga con garantía de resultados.",
  ctaText: "Solicitar inspección",
  ctaUrl: "/agendar",
  secondaryCtaText: "Conoce al equipo",
  secondaryCtaUrl: "/especialistas",
};

export const services = [
  {
    title: "Control de Roedores",
    slug: "control-roedores",
    short: "Eliminamos ratones y ratas con trampas y cebos seguros para tu familia.",
    long: "Tratamiento completo para eliminar la presencia de roedores en tu hogar o negocio. Incluye sellado de entradas y seguimiento post-tratamiento.",
    includes: ["Inspección de la propiedad", "Colocación de trampas y cebos", "Sellado de puntos de entrada", "Visita de seguimiento"],
    duration: "2-3 horas aprox.",
    priceFrom: 150,
    category: "roedores",
  },
  {
    title: "Fumigación de Cucarachas",
    slug: "fumigacion-cucarachas",
    short: "Tratamiento intensivo para cucarachas en cocina, baños y áreas de servicio.",
    long: "Aplicación de gel y sprays de efecto residual para eliminar cucarachas desde la raíz. Incluye tratamiento en grietas, esquinas y puntos de calor.",
    includes: ["Gel en grietas y esquinas", "Spray residual", "Recomendaciones preventivas", "Garantía de 30 días"],
    duration: "1-2 horas aprox.",
    priceFrom: 120,
    category: "cucarachas",
  },
  {
    title: "Tratamiento para Termitas",
    slug: "tratamiento-termitas",
    short: "Protección de madera y estructuras contra termitas subterráneas y de madera seca.",
    long: "Inspección y tratamiento especializado para termitas. Barrera química en suelo y tratamiento localizado en estructuras de madera.",
    includes: ["Inspección estructural", "Barrera química en suelo", "Tratamiento en madera afectada", "Reporte detallado"],
    duration: "3-5 horas aprox.",
    priceFrom: 350,
    category: "termitas",
  },
  {
    title: "Eliminación de Chinches de Cama",
    slug: "eliminacion-chinches",
    short: "Tratamiento térmico y químico para eliminar chinches en colchones, sillones y ropa.",
    long: "Protocolo intensivo de dos pasos: tratamiento térmico y aplicación de residual de larga duración. Las chinches no sobreviven a nuestra metodología.",
    includes: ["Inspección de colchones y muebles", "Tratamiento térmico", "Aplicación de residual", "Segunda visita de refuerzo"],
    duration: "4-6 horas aprox.",
    priceFrom: 280,
    category: "chinches",
  },
  {
    title: "Control de Hormigas",
    slug: "control-hormigas",
    short: "Eliminamos colonias de hormigas en interior y exterior con tratamiento de cebo.",
    long: "Localización del nido y aplicación de cebo específico para el tipo de hormiga. Tratamiento perimetral exterior para prevenir reinfestación.",
    includes: ["Identificación del tipo de hormiga", "Cebo para colonia", "Tratamiento perimetral", "Instrucciones preventivas"],
    duration: "1-2 horas aprox.",
    priceFrom: 130,
    category: "hormigas",
  },
  {
    title: "Retiro de Avispas y Abejas",
    slug: "retiro-avispas-abejas",
    short: "Retiro seguro de nidos de avispas y abejas en techo, árboles y estructuras.",
    long: "Remoción profesional de nidos activos con equipo de protección y técnicas que minimizan el riesgo. No matamos abejas nativas — las reubicamos.",
    includes: ["Evaluación del nido", "Remoción segura", "Tratamiento del área", "Sellado si aplica"],
    duration: "1-3 horas aprox.",
    priceFrom: 180,
    category: "avispas",
  },
  {
    title: "Inspección General",
    slug: "inspeccion-general",
    short: "Inspección completa de tu propiedad para detectar presencia o riesgo de plagas.",
    long: "Revisamos interior, exterior, sótano y ático. Te entregamos un reporte con hallazgos y recomendaciones específicas. Ideal antes de comprar una propiedad.",
    includes: ["Inspección de todas las áreas", "Reporte escrito", "Mapa de riesgo", "Cotización sin compromiso"],
    duration: "1-2 horas aprox.",
    priceFrom: 90,
    category: "inspeccion",
  },
  {
    title: "Fumigación General Preventiva",
    slug: "fumigacion-general",
    short: "Tratamiento preventivo completo para mantener tu hogar libre de plagas todo el año.",
    long: "Aplicación de productos de amplio espectro en interior y exterior. Ideal como mantenimiento trimestral para hogares y negocios.",
    includes: ["Tratamiento interior y exterior", "Productos de efecto residual", "Plan de mantenimiento trimestral disponible", "Garantía de 60 días"],
    duration: "2-3 horas aprox.",
    priceFrom: 200,
    category: "general",
  },
];

export const specialists = [
  {
    _id: "tech-001",
    slug: "carlos-ramirez",
    name: "Carlos Ramírez",
    specialty: "Control de Roedores y Termitas",
    specialtyCategory: "roedores",
    shortBio: "Técnico certificado con 8 años de experiencia en control de roedores y tratamientos de termitas en Charlotte, NC.",
    focusAreas: ["Control de roedores", "Tratamiento de termitas", "Sellado de estructuras", "Inspecciones residenciales"],
    useWhatsAppButton: true,
    photoUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    active: true,
  },
  {
    _id: "tech-002",
    slug: "ana-torres",
    name: "Ana Torres",
    specialty: "Inspectora Certificada de Plagas",
    specialtyCategory: "inspeccion",
    shortBio: "Inspectora certificada por el estado de NC con especialidad en detección temprana y prevención de infestaciones.",
    focusAreas: ["Inspecciones comerciales", "Reportes técnicos", "Prevención y mantenimiento", "Control de chinches"],
    useWhatsAppButton: true,
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80",
    active: true,
  },
  {
    _id: "tech-003",
    slug: "miguel-santos",
    name: "Miguel Santos",
    specialty: "Fumigación Residencial y Comercial",
    specialtyCategory: "general",
    shortBio: "Especialista en fumigación general para hogares y negocios. Más de 10 años protegiendo propiedades en Charlotte y alrededores.",
    focusAreas: ["Fumigación general", "Control de cucarachas", "Hormigas y avispas", "Mantenimiento trimestral"],
    useWhatsAppButton: true,
    photoUrl: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=800&q=80",
    active: true,
  },
];

export const promotions = [
  {
    _id: "promo-001",
    slug: "inspeccion-gratis",
    title: "Inspección Gratuita",
    label: "Sin costo",
    shortDescription: "Primera inspección sin cargo. Te entregamos un reporte completo y cotización sin compromiso.",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    featured: true,
    pinned: true,
    active: true,
    appliesTo: ["Inspección General"],
    categories: ["inspeccion"],
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
  },
  {
    _id: "promo-002",
    slug: "paquete-hogar-completo",
    title: "Paquete Hogar Completo – 10% OFF",
    label: "10% descuento",
    shortDescription: "Contrata 2 o más servicios y obtén 10% de descuento en el total. Aplica para hogares residenciales.",
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    featured: true,
    pinned: false,
    active: true,
    appliesTo: ["Roedores", "Cucarachas", "Hormigas", "General"],
    categories: ["general", "roedores", "cucarachas", "hormigas"],
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
  },
  {
    _id: "promo-003",
    slug: "mantenimiento-trimestral",
    title: "Plan Mantenimiento Trimestral",
    label: "Mejor precio",
    shortDescription: "3 visitas al año con 15% de descuento. Mantén tu hogar protegido todo el año con el menor costo por visita.",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    featured: false,
    pinned: false,
    active: true,
    appliesTo: ["Fumigación General", "Control de Hormigas"],
    categories: ["general", "hormigas"],
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
  },
];

export const prices = [
  { _id: "p-01", serviceTitle: "Inspección General",        category: "inspeccion", priceFrom: 90,  duration: "1-2 hrs",  note: "Primera inspección gratis" },
  { _id: "p-02", serviceTitle: "Control de Roedores",       category: "roedores",   priceFrom: 150, duration: "2-3 hrs",  note: "Incluye sellado de entradas" },
  { _id: "p-03", serviceTitle: "Fumigación de Cucarachas",  category: "cucarachas", priceFrom: 120, duration: "1-2 hrs",  note: "Garantía 30 días" },
  { _id: "p-04", serviceTitle: "Tratamiento para Termitas", category: "termitas",   priceFrom: 350, duration: "3-5 hrs",  note: "Incluye reporte estructural" },
  { _id: "p-05", serviceTitle: "Eliminación de Chinches",   category: "chinches",   priceFrom: 280, duration: "4-6 hrs",  note: "2 visitas incluidas" },
  { _id: "p-06", serviceTitle: "Control de Hormigas",       category: "hormigas",   priceFrom: 130, duration: "1-2 hrs",  note: "Interior y exterior" },
  { _id: "p-07", serviceTitle: "Retiro de Avispas/Abejas",  category: "avispas",    priceFrom: 180, duration: "1-3 hrs",  note: "Reubicación de abejas nativas" },
  { _id: "p-08", serviceTitle: "Fumigación General",        category: "general",    priceFrom: 200, duration: "2-3 hrs",  note: "Garantía 60 días" },
  { _id: "p-09", serviceTitle: "Plan Trimestral (3 visitas)",category: "general",   priceFrom: 510, duration: "Por visita",note: "15% de descuento vs precio unitario" },
  { _id: "p-10", serviceTitle: "Paquete Hogar Completo",    category: "general",    priceFrom: 380, duration: "4-6 hrs",  note: "Cubre 3 plagas simultáneas" },
];

export const faqs = [
  {
    _id: "faq-01",
    question: "¿Cuánto tiempo debo esperar para entrar a mi casa después de la fumigación?",
    answer: "Generalmente recomendamos esperar entre 2 y 4 horas con las ventanas abiertas antes de entrar. Para tratamientos de termitas o chinches, el tiempo puede ser mayor. Tu técnico te indicará el tiempo exacto.",
    category: "general",
    featured: true,
  },
  {
    _id: "faq-02",
    question: "¿Los productos que usan son seguros para niños y mascotas?",
    answer: "Sí. Utilizamos productos registrados por la EPA, seguros para uso residencial. Pedimos que niños y mascotas salgan del área tratada durante el servicio y las horas posteriores indicadas.",
    category: "general",
    featured: true,
  },
  {
    _id: "faq-03",
    question: "¿Tienen garantía si la plaga regresa?",
    answer: "Sí. La mayoría de nuestros servicios incluyen garantía de 30 a 60 días. Si la plaga regresa dentro de ese período, volvemos sin costo adicional.",
    category: "general",
    featured: true,
  },
  {
    _id: "faq-04",
    question: "¿Cuánto cuesta una inspección?",
    answer: "La primera inspección general es gratuita. Para inspecciones especializadas (termitas, chinches) el precio parte de $90 USD e incluye reporte escrito y cotización.",
    category: "inspeccion",
    featured: false,
  },
  {
    _id: "faq-05",
    question: "¿Cuántas visitas se necesitan para eliminar roedores?",
    answer: "Generalmente 2-3 visitas: una inicial para colocar trampas y sellar entradas, y una o dos de seguimiento para verificar que la infestación está controlada.",
    category: "roedores",
    featured: false,
  },
  {
    _id: "faq-06",
    question: "¿Por qué las termitas son tan peligrosas?",
    answer: "Las termitas destruyen madera desde adentro sin señales visibles. Una colonia puede consumir varios kilos de madera al año. La detección temprana evita daños estructurales costosos.",
    category: "termitas",
    featured: false,
  },
  {
    _id: "faq-07",
    question: "¿Cuánto tiempo tarda el tratamiento de chinches?",
    answer: "El tratamiento completo toma entre 4 y 6 horas. Incluye tratamiento térmico y aplicación de residual. Recomendamos una segunda visita a las 2 semanas para asegurar la eliminación total.",
    category: "chinches",
    featured: false,
  },
  {
    _id: "faq-08",
    question: "¿Atienden negocios y restaurantes?",
    answer: "Sí. Ofrecemos planes de mantenimiento para negocios, restaurantes, bodegas y cualquier espacio comercial. Los tratamientos se programan fuera de horario de operación.",
    category: "general",
    featured: false,
  },
];

export const gallery = [
  {
    _id: "g-01",
    type: "image",
    title: "Fumigación de cucarachas",
    category: "cucarachas",
    featured: true,
    active: true,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
  },
  {
    _id: "g-02",
    type: "image",
    title: "Técnico en campo",
    category: "general",
    featured: true,
    active: true,
    imageUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
  },
  {
    _id: "g-03",
    type: "image",
    title: "Inspección de roedores",
    category: "roedores",
    featured: false,
    active: true,
    imageUrl: "https://images.unsplash.com/photo-1601615588175-d81f02cbef0a?auto=format&fit=crop&w=800&q=80",
  },
];
