export default {
  name: "aboutSection",
  title: "Nosotros (Inicio)",
  type: "document",
  description: "Seccion Nosotros visible en Inicio y pagina Nosotros.",
  fieldsets: [
    { name: "home", title: "1) Bloque Nosotros en Inicio", options: { collapsible: true, collapsed: false } },
    { name: "page", title: "2) Pagina Nosotros", options: { collapsible: true, collapsed: false } },
    { name: "media", title: "3) Imagenes", options: { collapsible: true, collapsed: false } },
    { name: "cta", title: "4) Botones", options: { collapsible: true, collapsed: false } },
  ],
  fields: [
    {
      name: "title",
      title: "Titulo",
      type: "string",
      description: "Aqui editas el titulo de la seccion Nosotros.",
      fieldset: "home",
      validation: (R) => R.required().error("El titulo es obligatorio."),
    },
    {
      name: "intro",
      title: "Texto principal",
      type: "text",
      rows: 5,
      description: "Aqui editas el primer texto de presentacion.",
      fieldset: "home",
      validation: (R) => R.required().error("El texto principal es obligatorio."),
    },
    {
      name: "secondary",
      title: "Texto secundario",
      type: "text",
      rows: 5,
      description: "Aqui editas un segundo texto de apoyo.",
      fieldset: "home",
    },
    {
      name: "keyPoints",
      title: "Puntos clave",
      type: "array",
      description: "Aqui agregas beneficios o especialidades (maximo 6).",
      fieldset: "home",
      of: [{ type: "string" }],
      validation: (R) => R.max(6).warning("Recomendado: maximo 6 puntos."),
    },
    {
      name: "specialistsTitle",
      title: "Titulo de especialistas",
      type: "string",
      description: "Titulo del bloque de especialistas en pagina Nosotros.",
      fieldset: "page",
      initialValue: "Nuestros especialistas",
    },
    {
      name: "specialistsSubtitle",
      title: "Subtitulo de especialistas",
      type: "string",
      description: "Texto corto del bloque de especialistas.",
      fieldset: "page",
      initialValue: "Conoce a las personas que atienden cada especialidad en nuestra clinica.",
    },
    {
      name: "servicesTitle",
      title: "Titulo de especialidades",
      type: "string",
      description: "Titulo del bloque de servicios en pagina Nosotros.",
      fieldset: "page",
      initialValue: "Especialidades que atendemos",
    },
    {
      name: "servicesSubtitle",
      title: "Subtitulo de especialidades",
      type: "string",
      description: "Texto corto del bloque de servicios.",
      fieldset: "page",
      initialValue: "Atendemos diferentes necesidades de salud con enfoque integral.",
    },
    {
      name: "mainImage",
      title: "Imagen principal",
      type: "image",
      options: { hotspot: true },
      description: "Aqui subes la foto principal de Nosotros.",
      fieldset: "media",
      validation: (R) => R.required().error("La imagen principal es obligatoria."),
    },
    {
      name: "galleryImages",
      title: "Imagenes de apoyo",
      type: "array",
      description: "Aqui puedes subir hasta 4 imagenes adicionales.",
      fieldset: "media",
      of: [{ type: "image", options: { hotspot: true } }],
      validation: (R) => R.max(4).warning("Puedes subir maximo 4 imagenes de apoyo."),
    },
    {
      name: "ctaText",
      title: "Texto boton principal",
      type: "string",
      description: "Texto del boton principal (ejemplo: Agenda tu cita).",
      fieldset: "cta",
      initialValue: "Agenda tu cita",
    },
    {
      name: "ctaUrl",
      title: "Enlace boton principal",
      type: "string",
      description: "A donde lleva el boton principal. Ejemplo: /agendar",
      fieldset: "cta",
      initialValue: "/agendar",
      validation: (R) => R.required().error("El enlace del boton principal es obligatorio."),
    },
    {
      name: "secondaryCtaText",
      title: "Texto boton secundario",
      type: "string",
      description: "Texto del boton secundario (ejemplo: Conocenos mas).",
      fieldset: "cta",
      initialValue: "Conocenos mas",
    },
    {
      name: "secondaryCtaUrl",
      title: "Enlace boton secundario",
      type: "string",
      description: "A donde lleva el boton secundario. Ejemplo: /nosotros",
      fieldset: "cta",
      initialValue: "/nosotros",
      validation: (R) => R.required().error("El enlace del boton secundario es obligatorio."),
    },
  ],
  preview: {
    select: {
      title: "title",
      media: "mainImage",
    },
    prepare({ title, media }) {
      return {
        title: title || "Nosotros",
        subtitle: "Seccion del home",
        media,
      };
    },
  },
};
