export default {
  name: "aboutSection",
  title: "Nosotros (Inicio)",
  type: "document",
  description: "Seccion Nosotros visible en la pagina principal.",
  fields: [
    {
      name: "title",
      title: "Titulo",
      type: "string",
      description: "Aqui editas el titulo de la seccion Nosotros.",
      validation: (R) => R.required().error("El titulo es obligatorio."),
    },
    {
      name: "intro",
      title: "Texto principal",
      type: "text",
      rows: 5,
      description: "Aqui editas el primer texto de presentacion.",
      validation: (R) => R.required().error("El texto principal es obligatorio."),
    },
    {
      name: "secondary",
      title: "Texto secundario",
      type: "text",
      rows: 5,
      description: "Aqui editas un segundo texto de apoyo.",
    },
    {
      name: "keyPoints",
      title: "Puntos clave",
      type: "array",
      description: "Aqui agregas beneficios o especialidades (maximo 6).",
      of: [{ type: "string" }],
      validation: (R) => R.max(6).warning("Recomendado: maximo 6 puntos."),
    },
    {
      name: "mainImage",
      title: "Imagen principal",
      type: "image",
      options: { hotspot: true },
      description: "Aqui subes la foto principal de Nosotros.",
      validation: (R) => R.required().error("La imagen principal es obligatoria."),
    },
    {
      name: "galleryImages",
      title: "Imagenes de apoyo",
      type: "array",
      description: "Aqui puedes subir hasta 4 imagenes adicionales.",
      of: [{ type: "image", options: { hotspot: true } }],
      validation: (R) => R.max(4).warning("Puedes subir maximo 4 imagenes de apoyo."),
    },
    {
      name: "specialistsTitle",
      title: "Titulo de especialistas",
      type: "string",
      description: "Aqui editas el titulo del bloque de especialistas en pagina Nosotros.",
      initialValue: "Nuestros especialistas",
    },
    {
      name: "specialistsSubtitle",
      title: "Subtitulo de especialistas",
      type: "string",
      description: "Aqui editas el texto corto del bloque de especialistas.",
      initialValue: "Conoce a las personas que atienden cada especialidad en nuestra clinica.",
    },
    {
      name: "servicesTitle",
      title: "Titulo de especialidades",
      type: "string",
      description: "Aqui editas el titulo del bloque de servicios en pagina Nosotros.",
      initialValue: "Especialidades que atendemos",
    },
    {
      name: "servicesSubtitle",
      title: "Subtitulo de especialidades",
      type: "string",
      description: "Aqui editas el texto corto del bloque de servicios.",
      initialValue: "Atendemos diferentes necesidades de salud con enfoque integral.",
    },
    {
      name: "ctaText",
      title: "Texto boton principal",
      type: "string",
      description: "Aqui editas el texto del boton principal (ejemplo: Agenda tu cita).",
      initialValue: "Agenda tu cita",
    },
    {
      name: "ctaUrl",
      title: "Enlace boton principal",
      type: "string",
      description: "Aqui editas a donde lleva el boton principal. Ejemplo: /agendar",
      initialValue: "/agendar",
      validation: (R) => R.required().error("El enlace del boton principal es obligatorio."),
    },
    {
      name: "secondaryCtaText",
      title: "Texto boton secundario",
      type: "string",
      description: "Aqui editas el texto del boton secundario (ejemplo: Conocenos mas).",
      initialValue: "Conocenos mas",
    },
    {
      name: "secondaryCtaUrl",
      title: "Enlace boton secundario",
      type: "string",
      description: "Aqui editas a donde lleva el boton secundario. Ejemplo: /nosotros",
      initialValue: "/nosotros",
      validation: (R) => R.required().error("El enlace del boton secundario es obligatorio."),
    },
  ],
  preview: {
    select: {
      title: "title",
      media: "mainImage",
    },
    prepare({ title, media }) {
      return {
        title: title || "Nosotros",
        subtitle: "Seccion del home",
        media,
      };
    },
  },
};
