export default {
  name: "aboutSection",
  title: "Nosotros (Inicio)",
  type: "document",
  description: "Seccion Nosotros visible en Inicio y pagina Nosotros.",
  fieldsets: [
    { name: "home",   title: "1) Bloque Nosotros en Inicio (ES)", options: { collapsible: true, collapsed: false } },
    { name: "homeEn", title: "1b) About Us block — Homepage (EN)", options: { collapsible: true, collapsed: false } },
    { name: "page",   title: "2) Pagina Nosotros",                 options: { collapsible: true, collapsed: false } },
    { name: "media",  title: "3) Imagenes",                        options: { collapsible: true, collapsed: false } },
    { name: "cta",    title: "4) Botones",                         options: { collapsible: true, collapsed: false } },
  ],
  fields: [
    // ── Español ──────────────────────────────────────────────────
    {
      name: "title",
      title: "Titulo (ES)",
      type: "string",
      description: "Titulo de la seccion Nosotros en espanol.",
      fieldset: "home",
      validation: (R) => R.required().error("El titulo es obligatorio."),
    },
    {
      name: "intro",
      title: "Texto principal (ES)",
      type: "text",
      rows: 5,
      description: "Primer texto de presentacion en espanol.",
      fieldset: "home",
      validation: (R) => R.required().error("El texto principal es obligatorio."),
    },
    {
      name: "secondary",
      title: "Texto secundario (ES)",
      type: "text",
      rows: 5,
      description: "Segundo texto de apoyo en espanol.",
      fieldset: "home",
    },
    {
      name: "keyPoints",
      title: "Puntos clave (ES)",
      type: "array",
      description: "Beneficios en espanol (maximo 6). Ejemplo: Tecnicos certificados.",
      fieldset: "home",
      of: [{ type: "string" }],
      validation: (R) => R.max(6).warning("Recomendado: maximo 6 puntos."),
    },
    // ── English ──────────────────────────────────────────────────
    {
      name: "titleEn",
      title: "Title (EN)",
      type: "string",
      description: "About Us section title in English.",
      fieldset: "homeEn",
    },
    {
      name: "introEn",
      title: "Main text (EN)",
      type: "text",
      rows: 5,
      description: "First intro paragraph in English.",
      fieldset: "homeEn",
    },
    {
      name: "secondaryEn",
      title: "Secondary text (EN)",
      type: "text",
      rows: 5,
      description: "Second supporting paragraph in English.",
      fieldset: "homeEn",
    },
    {
      name: "keyPointsEn",
      title: "Key points (EN)",
      type: "array",
      description: "Benefits in English (max 6). Example: Certified technicians.",
      fieldset: "homeEn",
      of: [{ type: "string" }],
      validation: (R) => R.max(6).warning("Recommended: max 6 points."),
    },
    {
      name: "specialistsTitle",
      title: "Titulo de tecnicos",
      type: "string",
      description: "Titulo del bloque de tecnicos en pagina Nosotros.",
      fieldset: "page",
      initialValue: "Nuestros técnicos",
    },
    {
      name: "specialistsSubtitle",
      title: "Subtitulo de tecnicos",
      type: "string",
      description: "Texto corto del bloque de tecnicos.",
      fieldset: "page",
      initialValue: "Conoce al equipo certificado que protege tu hogar y negocio.",
    },
    {
      name: "servicesTitle",
      title: "Titulo de servicios",
      type: "string",
      description: "Titulo del bloque de servicios en pagina Nosotros.",
      fieldset: "page",
      initialValue: "Servicios que ofrecemos",
    },
    {
      name: "servicesSubtitle",
      title: "Subtitulo de servicios",
      type: "string",
      description: "Texto corto del bloque de servicios.",
      fieldset: "page",
      initialValue: "Control completo contra los principales tipos de plagas en Charlotte, NC.",
    },
    {
      name: "mainImage",
      title: "Imagen principal",
      type: "image",
      options: { hotspot: true },
      description: "Aqui subes la foto principal de Nosotros.",
      fieldset: "media",
      validation: (R) => R.required().error("La imagen principal es obligatoria."),
    },
    {
      name: "galleryImages",
      title: "Imagenes de apoyo",
      type: "array",
      description: "Aqui puedes subir hasta 4 imagenes adicionales.",
      fieldset: "media",
      of: [{ type: "image", options: { hotspot: true } }],
      validation: (R) => R.max(4).warning("Puedes subir maximo 4 imagenes de apoyo."),
    },
    {
      name: "galleryCarouselIntervalMs",
      title: "Velocidad carrusel imagenes de apoyo (ms)",
      type: "number",
      description:
        "Aqui defines cada cuantos milisegundos cambia la imagen en Home. Recomendado rapido: 1800 a 2800.",
      fieldset: "media",
      initialValue: 2200,
      validation: (R) =>
        R.min(1200)
          .max(10000)
          .warning("Usa un valor entre 1200 y 10000 ms."),
    },
    {
      name: "ctaText",
      title: "Texto boton principal",
      type: "string",
      description: "Texto del boton principal (ejemplo: Solicitar servicio).",
      fieldset: "cta",
      initialValue: "Solicitar servicio",
    },
    {
      name: "ctaUrl",
      title: "Enlace boton principal",
      type: "string",
      description: "A donde lleva el boton principal. Ejemplo: /agendar",
      fieldset: "cta",
      initialValue: "/agendar",
      validation: (R) => R.required().error("El enlace del boton principal es obligatorio."),
    },
    {
      name: "secondaryCtaText",
      title: "Texto boton secundario",
      type: "string",
      description: "Texto del boton secundario (ejemplo: Conocenos mas).",
      fieldset: "cta",
      initialValue: "Conocenos mas",
    },
    {
      name: "secondaryCtaUrl",
      title: "Enlace boton secundario",
      type: "string",
      description: "A donde lleva el boton secundario. Ejemplo: /nosotros",
      fieldset: "cta",
      initialValue: "/nosotros",
      validation: (R) => R.required().error("El enlace del boton secundario es obligatorio."),
    },
  ],
  preview: {
    select: {
      title: "title",
      media: "mainImage",
    },
    prepare({ title, media }) {
      return {
        title: title || "Nosotros",
        subtitle: "Seccion del home",
        media,
      };
    },
  },
};
