export default {
  name: "businessInfo",
  title: "Informacion del negocio",
  type: "document",
  description: "Datos generales visibles en header, inicio, contacto, ubicacion y pie de pagina.",
  fieldsets: [
    { name: "general", title: "1) Header", options: { collapsible: true, collapsed: false } },
    {
      name: "sharePreview",
      title: "2) Compartir enlace (WhatsApp/Facebook)",
      options: { collapsible: true, collapsed: false },
    },
    { name: "home", title: "3) Inicio", options: { collapsible: true, collapsed: false } },
    { name: "location", title: "4) Ubicacion", options: { collapsible: true, collapsed: false } },
    { name: "contact", title: "5) Contacto", options: { collapsible: true, collapsed: false } },
    { name: "social", title: "6) Redes", options: { collapsible: true, collapsed: false } },
    { name: "footer", title: "7) Pie de pagina", options: { collapsible: true, collapsed: false } },
  ],
  fields: [
    {
      name: "name",
      title: "Nombre del negocio",
      type: "string",
      description: "Texto principal del Header.",
      fieldset: "general",
      validation: (R) => R.required().error("El nombre del negocio es obligatorio."),
    },
    {
      name: "area",
      title: "Subtexto del Header",
      type: "string",
      description: "Texto corto que aparece debajo del nombre en el Header.",
      fieldset: "general",
    },
    {
      name: "logoImage",
      title: "Logo del negocio (Header y Footer)",
      type: "image",
      description:
        "Aqui subes el logo principal que se muestra en encabezado y pie de pagina. Nota: esto no cambia el icono de la pestana (favicon). El favicon se ajusta en /public/favicon-light.svg y /public/favicon-dark.svg.",
      options: { hotspot: true },
      fieldset: "general",
    },
    {
      name: "hoursText",
      title: "Texto de horario en Header",
      type: "string",
      description: "Ejemplo: Horario de hoy: lunes de 10 a.m. a 6 p.m.",
      fieldset: "general",
    },

    {
      name: "socialShareTitle",
      title: "Titulo para compartir enlace",
      type: "string",
      description:
        "Aqui estamos editando este contenido. Este titulo aparece cuando pegas tu link en WhatsApp, Facebook u otras apps.",
      fieldset: "sharePreview",
      validation: (R) => R.max(80).warning("Recomendado: maximo 80 caracteres."),
    },
    {
      name: "socialShareDescription",
      title: "Descripcion para compartir enlace",
      type: "text",
      rows: 3,
      description:
        "Aqui estamos editando este contenido. Esta descripcion aparece debajo del titulo en la vista previa del link.",
      fieldset: "sharePreview",
      validation: (R) => R.max(180).warning("Recomendado: maximo 180 caracteres."),
    },
    {
      name: "socialShareImage",
      title: "Imagen para compartir enlace",
      type: "image",
      options: { hotspot: true },
      description:
        "Aqui subes la foto de vista previa cuando compartes el link. Puedes cambiarla y volver a subirla cuando quieras.",
      fieldset: "sharePreview",
    },

    {
      name: "homeHeroEyebrow",
      title: "Texto pequeno superior en Inicio",
      type: "string",
      description: "Aqui editas el texto pequeno sobre el titulo principal.",
      fieldset: "home",
    },
    {
      name: "homeHeroTitle",
      title: "Titulo principal en Inicio",
      type: "string",
      description: "Aqui editas el titulo grande de portada.",
      fieldset: "home",
    },
    {
      name: "homeHeroSubtitle",
      title: "Texto de apoyo en Inicio",
      type: "text",
      rows: 3,
      description: "Ejemplo: Mas de 20 anos cuidando la salud de tus pies.",
      fieldset: "home",
    },
    {
      name: "homeHeroImage",
      title: "Imagen principal en Inicio",
      type: "image",
      options: { hotspot: true },
      description: "Aqui subes la imagen principal de portada.",
      fieldset: "home",
    },
    {
      name: "homeHeroCarouselImages",
      title: "Imagenes del carrusel en Inicio",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      description: "Opcional. Si agregas varias imagenes, el hero rota automaticamente sin botones.",
      fieldset: "home",
      validation: (R) => R.max(8).warning("Recomendado: maximo 8 imagenes."),
    },
    {
      name: "homeHeroCarouselIntervalMs",
      title: "Velocidad del carrusel en Inicio",
      type: "number",
      description: "Tiempo entre imagenes. Recomendado: 6000 ms (6 segundos).",
      fieldset: "home",
      initialValue: 5000,
      options: {
        list: [
          { title: "4 segundos", value: 4000 },
          { title: "6 segundos", value: 6000 },
          { title: "8 segundos", value: 8000 },
          { title: "10 segundos", value: 10000 },
        ],
        layout: "dropdown",
      },
      validation: (R) =>
        R.min(3000)
          .max(12000)
          .warning("Usa un valor entre 3000 y 12000 milisegundos."),
    },
    {
      name: "homePrimaryCtaText",
      title: "Boton principal en Inicio",
      type: "string",
      description: "Aqui editas el texto del boton principal.",
      fieldset: "home",
      initialValue: "Agenda tu cita",
    },
    {
      name: "homePrimaryCtaUrl",
      title: "Enlace boton principal",
      type: "string",
      description: "Aqui editas el enlace del boton principal. Ejemplo: /agendar",
      fieldset: "home",
      initialValue: "/agendar",
    },
    {
      name: "homeSecondaryCtaText",
      title: "Boton secundario en Inicio",
      type: "string",
      description: "Aqui editas el texto del boton secundario.",
      fieldset: "home",
      initialValue: "Nuestros servicios",
    },
    {
      name: "homeSecondaryCtaUrl",
      title: "Enlace boton secundario",
      type: "string",
      description: "Aqui editas el enlace del boton secundario. Ejemplo: /servicios",
      fieldset: "home",
      initialValue: "/servicios",
    },
    {
      name: "homePromotionsTitle",
      title: "Titulo de promociones en Inicio",
      type: "string",
      description: "Aqui editas el titulo del carrusel de promociones.",
      fieldset: "home",
    },
    {
      name: "homePromotionsSubtitle",
      title: "Texto corto de promociones en Inicio",
      type: "string",
      description: "Aqui editas el subtitulo del carrusel.",
      fieldset: "home",
      validation: (R) => R.max(150).warning("Recomendado: maximo 150 caracteres."),
    },
    {
      name: "homePromotionFallbackImage",
      title: "Imagen base para promociones",
      type: "image",
      options: { hotspot: true },
      description: "Aqui subes la imagen base cuando una promocion no tiene foto.",
      fieldset: "home",
    },

    {
      name: "address",
      title: "Direccion completa",
      type: "string",
      description: "Direccion usada en Ubicacion, Contacto y Agenda.",
      fieldset: "location",
      validation: (R) => R.required().error("La direccion es obligatoria."),
    },
    {
      name: "mapsUrl",
      title: "URL de Google Maps",
      type: "url",
      description: "Enlace para abrir mapa externo.",
      fieldset: "location",
      validation: (R) => R.uri({ scheme: ["http", "https"] }),
    },
    {
      name: "locationZoneText",
      title: "Zona para como llegar",
      type: "string",
      description: "Ejemplo: Sta. Maria Tulpetlac, Ecatepec (sobre Via Morelos).",
      fieldset: "location",
    },
    {
      name: "locationReferencesText",
      title: "Referencias para llegar",
      type: "string",
      description: "Ejemplo: Cerca de Plaza X | A un lado de Tienda Y | Frente a Parada Z.",
      fieldset: "location",
    },
    {
      name: "locationParkingText",
      title: "Estacionamiento",
      type: "string",
      description: "Ejemplo: En calle / cercano / propio.",
      fieldset: "location",
    },
    {
      name: "locationAccessText",
      title: "Acceso",
      type: "string",
      description: "Ejemplo: Planta baja / con escalones.",
      fieldset: "location",
    },
    {
      name: "locationGuideTips",
      title: "Guia rapida (tips)",
      type: "array",
      of: [{ type: "string" }],
      description: "Agrega hasta 3 tips cortos para llegar y asistir.",
      fieldset: "location",
      validation: (R) => R.max(3).warning("Recomendado: maximo 3 tips."),
    },
    {
      name: "locationFacadeImage",
      title: "Foto de fachada o entrada",
      type: "image",
      options: { hotspot: true },
      description: "Sube una foto clara de la fachada o entrada para que te ubiquen rapido.",
      fieldset: "location",
    },

    {
      name: "phone",
      title: "Telefono visible",
      type: "string",
      description: "Telefono principal en Header y Contacto.",
      fieldset: "contact",
    },
    {
      name: "whatsappCitasNumber",
      title: "WhatsApp citas (solo numero)",
      type: "string",
      description: "Pega solo numeros, ejemplo 525512345678.",
      fieldset: "contact",
    },

    {
      name: "facebookUrl",
      title: "URL de Facebook",
      type: "url",
      description: "Aqui editas el link de Facebook.",
      fieldset: "social",
      validation: (R) => R.uri({ scheme: ["http", "https"] }),
    },
    {
      name: "instagramUrl",
      title: "URL de Instagram",
      type: "url",
      description: "Aqui editas el link de Instagram.",
      fieldset: "social",
      validation: (R) => R.uri({ scheme: ["http", "https"] }),
    },
    {
      name: "tiktokUrl",
      title: "URL de TikTok",
      type: "url",
      description: "Aqui editas el link de TikTok.",
      fieldset: "social",
      validation: (R) => R.uri({ scheme: ["http", "https"] }),
    },

    {
      name: "footerMenuTitle",
      title: "Titulo columna menu (pie de pagina)",
      type: "string",
      description: "Aqui editas el titulo de la columna Menu.",
      fieldset: "footer",
      initialValue: "Menu",
    },
    {
      name: "footerSiteTitle",
      title: "Titulo columna sitio (pie de pagina)",
      type: "string",
      description: "Aqui editas el titulo de la columna Sobre el sitio.",
      fieldset: "footer",
      initialValue: "Sobre el sitio",
    },
    {
      name: "footerPrivacyUrl",
      title: "URL Aviso de privacidad",
      type: "string",
      description: "Aqui editas el enlace de aviso de privacidad.",
      fieldset: "footer",
      initialValue: "/privacidad",
    },
    {
      name: "footerNoticesUrl",
      title: "URL Comunicados",
      type: "string",
      description: "Aqui editas el enlace de comunicados o noticias.",
      fieldset: "footer",
      initialValue: "/comunicados",
    },
    {
      name: "footerCopyrightText",
      title: "Texto inferior de copyright",
      type: "string",
      description: "Aqui editas el texto de copyright del pie de pagina.",
      fieldset: "footer",
      initialValue: "Todos los derechos reservados.",
    },
    {
      name: "footerProjectSignature",
      title: "Firma del proyecto (solo lectura)",
      type: "string",
      description: "Campo informativo no editable.",
      fieldset: "footer",
      initialValue: "Proyecto firmado por Abraham Jimenez Valdes Dev",
      readOnly: true,
    },
  ],
  preview: { select: { title: "name", subtitle: "address", media: "logoImage" } },
};
