export default {
  name: "businessInfo",
  title: "Informacion del negocio",
  type: "document",
  description: "Datos generales visibles en encabezado, inicio y pie de pagina.",
  fieldsets: [
    { name: "general", title: "General", options: { collapsible: true, collapsed: false } },
    { name: "contact", title: "Contacto", options: { collapsible: true, collapsed: false } },
    { name: "location", title: "Ubicacion", options: { collapsible: true, collapsed: false } },
    { name: "home", title: "Inicio", options: { collapsible: true, collapsed: false } },
    { name: "social", title: "Redes", options: { collapsible: true, collapsed: false } },
    { name: "footer", title: "Pie de pagina", options: { collapsible: true, collapsed: false } },
  ],
  fields: [
    { name: "name", title: "Nombre del negocio", type: "string", description: "Aqui editas el nombre principal del negocio.", fieldset: "general", validation: (R) => R.required().error("El nombre del negocio es obligatorio.") },
    { name: "area", title: "Zona o colonia", type: "string", description: "Aqui editas la zona que aparece bajo el nombre.", fieldset: "general" },
    { name: "logoImage", title: "Logo del negocio", type: "image", description: "Aqui subes el logo principal del encabezado.", options: { hotspot: true }, fieldset: "general" },
    { name: "address", title: "Direccion completa", type: "string", description: "Aqui editas la direccion visible en la web.", fieldset: "general", validation: (R) => R.required().error("La direccion es obligatoria.") },
    { name: "phone", title: "Telefono visible", type: "string", description: "Aqui editas el telefono principal.", fieldset: "contact" },
    { name: "mapsUrl", title: "URL de Google Maps", type: "url", description: "Pega el enlace de Google Maps del negocio.", fieldset: "contact", validation: (R) => R.uri({ scheme: ["http", "https"] }) },
    {
      name: "hoursText",
      title: "Horarios",
      type: "string",
      description: "Usa formato claro: Lunes a viernes 10:00 a 18:00 · Sabado 10:00 a 16:00 · Domingo cerrado.",
      fieldset: "contact",
    },
    { name: "whatsappCitasNumber", title: "WhatsApp citas (solo numero)", type: "string", description: "Pega solo numeros, ejemplo 525512345678.", fieldset: "contact" },
    { name: "locationZoneText", title: "Zona para como llegar", type: "string", description: "Ejemplo: Sta. Maria Tulpetlac, Ecatepec (sobre Via Morelos).", fieldset: "location" },
    { name: "locationReferencesText", title: "Referencias para llegar", type: "string", description: "Ejemplo: Cerca de Plaza X | A un lado de Tienda Y | Frente a Parada Z.", fieldset: "location" },
    { name: "locationParkingText", title: "Estacionamiento", type: "string", description: "Ejemplo: En calle / cercano / propio.", fieldset: "location" },
    { name: "locationAccessText", title: "Acceso", type: "string", description: "Ejemplo: Planta baja / con escalones.", fieldset: "location" },
    {
      name: "locationGuideTips",
      title: "Guia rapida (tips)",
      type: "array",
      of: [{ type: "string" }],
      description: "Agrega hasta 3 tips cortos para llegar y asistir.",
      fieldset: "location",
      validation: (R) => R.max(3).warning("Recomendado: maximo 3 tips."),
    },
    {
      name: "locationFacadeImage",
      title: "Foto de fachada o entrada",
      type: "image",
      options: { hotspot: true },
      description: "Sube una foto clara de la fachada o entrada para que te ubiquen rapido.",
      fieldset: "location",
    },

    { name: "homeHeroEyebrow", title: "Texto pequeno superior en Inicio", type: "string", description: "Aqui editas el texto pequeno sobre el titulo principal.", fieldset: "home" },
    { name: "homeHeroTitle", title: "Titulo principal en Inicio", type: "string", description: "Aqui editas el titulo grande de portada.", fieldset: "home" },
    {
      name: "homeHeroSubtitle",
      title: "Texto de apoyo en Inicio",
      type: "text",
      rows: 3,
      description: "Ejemplo: Mas de 20 anos cuidando la salud de tus pies.",
      fieldset: "home",
    },
    { name: "homeHeroImage", title: "Imagen principal en Inicio", type: "image", options: { hotspot: true }, description: "Aqui subes la imagen principal de portada.", fieldset: "home" },
    { name: "homePrimaryCtaText", title: "Boton principal en Inicio", type: "string", description: "Aqui editas el texto del boton principal.", fieldset: "home", initialValue: "Agenda tu cita" },
    { name: "homePrimaryCtaUrl", title: "Enlace boton principal", type: "string", description: "Aqui editas el enlace del boton principal. Ejemplo: /agendar", fieldset: "home", initialValue: "/agendar" },
    { name: "homeSecondaryCtaText", title: "Boton secundario en Inicio", type: "string", description: "Aqui editas el texto del boton secundario.", fieldset: "home", initialValue: "Nuestros servicios" },
    { name: "homeSecondaryCtaUrl", title: "Enlace boton secundario", type: "string", description: "Aqui editas el enlace del boton secundario. Ejemplo: /servicios", fieldset: "home", initialValue: "/servicios" },
    { name: "homePromotionsTitle", title: "Titulo de promociones en Inicio", type: "string", description: "Aqui editas el titulo del carrusel de promociones.", fieldset: "home" },
    { name: "homePromotionsSubtitle", title: "Texto corto de promociones en Inicio", type: "string", description: "Aqui editas el subtitulo del carrusel.", fieldset: "home", validation: (R) => R.max(150).warning("Recomendado: maximo 150 caracteres.") },
    { name: "homePromotionFallbackImage", title: "Imagen base para promociones", type: "image", options: { hotspot: true }, description: "Aqui subes la imagen base cuando una promocion no tiene foto.", fieldset: "home" },

    { name: "facebookUrl", title: "URL de Facebook", type: "url", description: "Aqui editas el link de Facebook.", fieldset: "social", validation: (R) => R.uri({ scheme: ["http", "https"] }) },
    { name: "instagramUrl", title: "URL de Instagram", type: "url", description: "Aqui editas el link de Instagram.", fieldset: "social", validation: (R) => R.uri({ scheme: ["http", "https"] }) },
    { name: "tiktokUrl", title: "URL de TikTok", type: "url", description: "Aqui editas el link de TikTok.", fieldset: "social", validation: (R) => R.uri({ scheme: ["http", "https"] }) },

    { name: "footerMenuTitle", title: "Titulo columna menu (pie de pagina)", type: "string", description: "Aqui editas el titulo de la columna Menu.", fieldset: "footer", initialValue: "Menu" },
    { name: "footerSiteTitle", title: "Titulo columna sitio (pie de pagina)", type: "string", description: "Aqui editas el titulo de la columna Sobre el sitio.", fieldset: "footer", initialValue: "Sobre el sitio" },
    { name: "footerPrivacyUrl", title: "URL Aviso de privacidad", type: "string", description: "Aqui editas el enlace de aviso de privacidad.", fieldset: "footer", initialValue: "/privacidad" },
    { name: "footerNoticesUrl", title: "URL Comunicados", type: "string", description: "Aqui editas el enlace de comunicados o noticias.", fieldset: "footer", initialValue: "/comunicados" },
    { name: "footerCopyrightText", title: "Texto inferior de copyright", type: "string", description: "Aqui editas el texto de copyright del pie de pagina.", fieldset: "footer", initialValue: "Todos los derechos reservados." },
    {
      name: "footerProjectSignature",
      title: "Firma del proyecto (solo lectura)",
      type: "string",
      description: "Campo informativo no editable.",
      fieldset: "footer",
      initialValue: "Proyecto firmado por Abraham Jimenez Valdes Dev",
      readOnly: true,
    },
  ],
  preview: { select: { title: "name", subtitle: "address", media: "logoImage" } },
};
